CREATE DATABASE IF NOT EXISTS sistemashaq
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

USE sistemashaq;

CREATE TABLE IF NOT EXISTS areas (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  nombre VARCHAR(100) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  CONSTRAINT uq_areas_nombre UNIQUE (nombre)
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

INSERT IGNORE INTO areas (nombre) VALUES
  ('DO'), ('ENFERMERIA'), ('ADMINISTRACION Y CONTABILIDAD'),
  ('RELACIONES PUBLICAS'), ('ADMISION'), ('LABORATORIO'), ('IMAGEN'),
  ('CONTROL DE INFECCIONES'), ('CONTROL HOSPITALARIO'), ('TERAPIA'),
  ('QUIROFANO');

CREATE TABLE IF NOT EXISTS equipos (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  serial_number VARCHAR(100) NOT NULL,
  area VARCHAR(100) NOT NULL,
  responsable VARCHAR(150) NOT NULL,
  ip_address VARCHAR(45) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
    ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  CONSTRAINT uq_equipos_serial UNIQUE (serial_number),
  CONSTRAINT uq_equipos_ip UNIQUE (ip_address),
  INDEX idx_equipos_area (area)
) ENGINE=InnoDB
  DEFAULT CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS auditoria_2026 (
  equipo_id BIGINT UNSIGNED NOT NULL,
  revision_software BOOLEAN NOT NULL DEFAULT FALSE,
  antivirus BOOLEAN NOT NULL DEFAULT FALSE,
  usb BOOLEAN NOT NULL DEFAULT FALSE,
  paginas_no_autorizadas BOOLEAN NOT NULL DEFAULT FALSE,
  escritorio BOOLEAN NOT NULL DEFAULT FALSE,
  tiempo_bloqueo BOOLEAN NOT NULL DEFAULT FALSE,
  bloqueo_configuracion BOOLEAN NOT NULL DEFAULT FALSE,
  glpi BOOLEAN NOT NULL DEFAULT FALSE,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (equipo_id),
  CONSTRAINT fk_auditoria_equipo FOREIGN KEY (equipo_id)
    REFERENCES equipos (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- Datos obtenidos bajo demanda desde el soporte oficial de Lenovo.
CREATE TABLE IF NOT EXISTS informacion_lenovo (
  equipo_id BIGINT UNSIGNED NOT NULL,
  modelo VARCHAR(255) NULL,
  mtm VARCHAR(100) NULL,
  familia VARCHAR(255) NULL,
  configuracion_original TEXT NULL,
  estado_garantia VARCHAR(100) NULL,
  inicio_garantia DATE NULL,
  fin_garantia DATE NULL,
  consultado_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (equipo_id),
  CONSTRAINT fk_lenovo_equipo FOREIGN KEY (equipo_id)
    REFERENCES equipos (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS laptops (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  serial_number VARCHAR(100) NOT NULL,
  area VARCHAR(100) NOT NULL,
  responsable VARCHAR(150) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  CONSTRAINT uq_laptops_serial UNIQUE (serial_number),
  INDEX idx_laptops_area (area)
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS informacion_lenovo_laptops (
  laptop_id BIGINT UNSIGNED NOT NULL,
  modelo VARCHAR(255) NULL,
  mtm VARCHAR(100) NULL,
  familia VARCHAR(255) NULL,
  configuracion_original TEXT NULL,
  estado_garantia VARCHAR(100) NULL,
  inicio_garantia DATE NULL,
  fin_garantia DATE NULL,
  consultado_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (laptop_id),
  CONSTRAINT fk_lenovo_laptop FOREIGN KEY (laptop_id)
    REFERENCES laptops (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS servidores (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  serial_number VARCHAR(100) NOT NULL,
  nombre_servidor VARCHAR(150) NOT NULL,
  ip_address VARCHAR(45) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  CONSTRAINT uq_servidores_serial UNIQUE (serial_number),
  CONSTRAINT uq_servidores_ip UNIQUE (ip_address),
  INDEX idx_servidores_nombre (nombre_servidor)
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS ipads (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  serial_number VARCHAR(100) NULL,
  area VARCHAR(100) NOT NULL,
  responsable VARCHAR(150) NOT NULL,
  generacion ENUM('novena', 'decima') NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  CONSTRAINT uq_ipads_serial UNIQUE (serial_number),
  INDEX idx_ipads_area (area)
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
