CREATE DATABASE IF NOT EXISTS sistemashaq
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

USE sistemashaq;

CREATE TABLE IF NOT EXISTS areas (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  nombre VARCHAR(100) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  CONSTRAINT uq_areas_nombre UNIQUE (nombre)
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

INSERT IGNORE INTO areas (nombre) VALUES
  ('DO'), ('ENFERMERIA'), ('ADMINISTRACION Y CONTABILIDAD'),
  ('RELACIONES PUBLICAS'), ('ADMISION'), ('LABORATORIO'), ('IMAGEN'),
  ('CONTROL DE INFECCIONES'), ('CONTROL HOSPITALARIO'), ('TERAPIA'),
  ('QUIROFANO');

CREATE TABLE IF NOT EXISTS equipos (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  serial_number VARCHAR(100) NOT NULL,
  area VARCHAR(100) NOT NULL,
  ip_address VARCHAR(45) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
    ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  CONSTRAINT uq_equipos_serial UNIQUE (serial_number),
  CONSTRAINT uq_equipos_ip UNIQUE (ip_address),
  INDEX idx_equipos_area (area)
) ENGINE=InnoDB
  DEFAULT CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS auditoria_2026 (
  equipo_id BIGINT UNSIGNED NOT NULL,
  revision_software BOOLEAN NOT NULL DEFAULT FALSE,
  antivirus BOOLEAN NOT NULL DEFAULT FALSE,
  usb BOOLEAN NOT NULL DEFAULT FALSE,
  paginas_no_autorizadas BOOLEAN NOT NULL DEFAULT FALSE,
  escritorio BOOLEAN NOT NULL DEFAULT FALSE,
  tiempo_bloqueo BOOLEAN NOT NULL DEFAULT FALSE,
  glpi_antivirus BOOLEAN NOT NULL DEFAULT FALSE,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (equipo_id),
  CONSTRAINT fk_auditoria_equipo FOREIGN KEY (equipo_id)
    REFERENCES equipos (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
